---
- hosts: all
  remote_user: ubuntu2
  become: true


  tasks:
   - name: enable and install nginx
     apt:
       name: nginx
       state: latest


   - name: start nginx
     service:
       name: nginx
       state: started
