---
- hosts: all
  remote_user: remote
  become: yes
  become_user: root
  gather_facts: yes
  tasks:
  
      
  - ansible.builtin.shell:
      cmd: curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
  
  - ansible.builtin.shell:
      cmd:  wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg 
  
  - ansible.builtin.command:
      cmd: echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list

  - ansible.builtin.apt:
      name: terraform
      state: present
      update_cache: true
      force: yes
